name: Build-Release-Publish

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: AtCoderLibrary.sln

jobs:
  get-version:
    uses: kzrnm/dotnet-actions/.github/workflows/get-version.yml@v1
    with:
      project-path: Directory.Build.props

  format:
    uses: kzrnm/dotnet-actions/.github/workflows/format.yml@v1
    with:
      target: AtCoderLibrary.sln
      dotnet-version: 6.0.x

  library-checker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: checkout library-checker-problems
        uses: actions/checkout@v2
        with:
          repository: yosupo06/library-checker-problems
          path: library-checker-problems
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            6.0.x
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install python dependencies
        working-directory: library-checker-problems
        run: |
          python -m pip install --upgrade pip
          pip install --user -r requirements.txt
      - name: Build
        run: dotnet build ${{ env.WORKFLOW_BUILD_SLN }}
      - name: Run
        run: |
          ulimit -s unlimited
          dotnet run --project Test/AtCoderLibrary.LibraryChecker/AtCoderLibrary.LibraryChecker.csproj ${{ github.workspace }}/library-checker-problems

  build:
    runs-on: ubuntu-latest
    needs: [get-version]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.0.x
            3.1.x
            6.0.x
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build
        run: dotnet build ${{ env.WORKFLOW_BUILD_SLN }} -c Release
      - name: Test
        run: dotnet test ${{ env.WORKFLOW_BUILD_SLN }} --no-build --logger GitHubActions -c Release
      - uses: actions/upload-artifact@v1
        if: ${{ needs.get-version.outputs.is-new == 'true' }}
        with:
          name: dist
          path: bin/Packages/Release

  publish:
    needs: [get-version, build, format, library-checker]
    if: ${{ needs.get-version.outputs.is-new == 'true' }}
    uses: kzrnm/dotnet-actions/.github/workflows/publish.yml@v1
    with:
      artifact-name: dist
      version: ${{ needs.get-version.outputs.version }}
      is-prerelease: ${{ needs.get-version.outputs.is-prerelease == 'true' }}
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
